2022-02-18 13:08:06,424 INFO    MainThread:15407 [wandb_setup.py:_flush():71] setting env: {}
2022-02-18 13:08:06,424 INFO    MainThread:15407 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-18 13:08:06,424 INFO    MainThread:15407 [wandb_init.py:_log_setup():371] Logging user logs to /home/simon/CDE_UBS/thesis/testing/wandb/run-20220218_130806-2jsq34nj/logs/debug.log
2022-02-18 13:08:06,424 INFO    MainThread:15407 [wandb_init.py:_log_setup():372] Logging internal logs to /home/simon/CDE_UBS/thesis/testing/wandb/run-20220218_130806-2jsq34nj/logs/debug-internal.log
2022-02-18 13:08:06,424 INFO    MainThread:15407 [wandb_init.py:_jupyter_setup():321] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f380104f450>
2022-02-18 13:08:06,425 INFO    MainThread:15407 [wandb_init.py:init():404] calling init triggers
2022-02-18 13:08:06,425 INFO    MainThread:15407 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {}
2022-02-18 13:08:06,425 INFO    MainThread:15407 [wandb_init.py:init():426] re-initializing run, found existing run on stack: 3gnxt8ob
2022-02-18 13:08:06,427 INFO    MainThread:15407 [wandb_run.py:finish():1457] finishing run simon-donike/SRCNN/3gnxt8ob
2022-02-18 13:08:06,428 INFO    MainThread:15407 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-02-18 13:08:06,429 INFO    MainThread:15407 [wandb_run.py:_restore():1752] restore
2022-02-18 13:08:07,385 INFO    MainThread:15407 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 761
}

2022-02-18 13:08:07,709 INFO    MainThread:15407 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 761
}

2022-02-18 13:08:08,020 INFO    MainThread:15407 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 25181
}

2022-02-18 13:08:08,125 INFO    MainThread:15407 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 25181
}

2022-02-18 13:08:08,227 INFO    MainThread:15407 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 25181
}

2022-02-18 13:08:08,330 INFO    MainThread:15407 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25181
  total_bytes: 25181
}

2022-02-18 13:08:08,433 INFO    MainThread:15407 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25181
  total_bytes: 25181
}

2022-02-18 13:08:08,536 INFO    MainThread:15407 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25181
  total_bytes: 25181
}

2022-02-18 13:08:08,638 INFO    MainThread:15407 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25181
  total_bytes: 25181
}

2022-02-18 13:08:08,740 INFO    MainThread:15407 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25181
  total_bytes: 25181
}

2022-02-18 13:08:09,298 INFO    MainThread:15407 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25181
  total_bytes: 25181
}

2022-02-18 13:08:09,738 INFO    MainThread:15407 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25181
  total_bytes: 25181
}
local_info {
}

2022-02-18 13:08:11,470 INFO    MainThread:15407 [wandb_run.py:_append_files():2180] logging synced files
2022-02-18 13:08:11,477 INFO    MainThread:15407 [wandb_init.py:init():460] starting backend
2022-02-18 13:08:11,477 INFO    MainThread:15407 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-18 13:08:11,484 INFO    MainThread:15407 [backend.py:ensure_launched():216] starting backend process...
2022-02-18 13:08:11,785 INFO    MainThread:15407 [backend.py:ensure_launched():222] started backend process with pid: 15691
2022-02-18 13:08:11,787 INFO    MainThread:15407 [wandb_init.py:init():469] backend started and connected
2022-02-18 13:08:11,824 INFO    MainThread:15407 [wandb_run.py:_label_probe_notebook():911] probe notebook
2022-02-18 13:08:11,825 INFO    MainThread:15407 [wandb_run.py:_label_probe_notebook():921] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-02-18 13:08:11,825 INFO    MainThread:15407 [wandb_init.py:init():533] updated telemetry
2022-02-18 13:08:12,653 INFO    MainThread:15407 [wandb_init.py:init():563] communicating current version
2022-02-18 13:08:13,853 INFO    MainThread:15407 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.10 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-02-18 13:08:13,854 INFO    MainThread:15407 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-02-18 13:08:14,066 INFO    MainThread:15407 [wandb_init.py:init():606] starting run threads in backend
2022-02-18 13:08:19,075 INFO    MainThread:15407 [wandb_run.py:_console_start():1810] atexit reg
2022-02-18 13:08:19,075 INFO    MainThread:15407 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-02-18 13:08:19,075 INFO    MainThread:15407 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-02-18 13:08:19,076 INFO    MainThread:15407 [wandb_run.py:_redirect():1745] Redirects installed.
2022-02-18 13:08:19,076 INFO    MainThread:15407 [wandb_init.py:init():633] run started, returning control to user process
2022-02-18 13:16:32,239 INFO    MainThread:15407 [wandb_init.py:_pause_backend():284] pausing backend
2022-02-18 13:16:32,239 INFO    MainThread:15407 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-18 13:25:59,328 INFO    MainThread:15407 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-02-18 13:25:59,330 INFO    MainThread:15407 [wandb_run.py:_restore():1752] restore
2022-02-18 13:26:00,141 INFO    MainThread:15407 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 761
}

2022-02-18 13:26:00,373 INFO    MainThread:15407 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 761
}

2022-02-18 13:26:00,483 INFO    MainThread:15407 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 25246
}

2022-02-18 13:26:00,588 INFO    MainThread:15407 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 25246
}

2022-02-18 13:26:00,694 INFO    MainThread:15407 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 25246
}

2022-02-18 13:26:00,798 INFO    MainThread:15407 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25246
  total_bytes: 25246
}

2022-02-18 13:26:00,903 INFO    MainThread:15407 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25246
  total_bytes: 25246
}

2022-02-18 13:26:01,007 INFO    MainThread:15407 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25246
  total_bytes: 25246
}

2022-02-18 13:26:01,110 INFO    MainThread:15407 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25246
  total_bytes: 25246
}

2022-02-18 13:26:01,213 INFO    MainThread:15407 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25246
  total_bytes: 25246
}

2022-02-18 13:26:01,316 INFO    MainThread:15407 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25246
  total_bytes: 25246
}

