2022-02-23 17:17:50,326 INFO    MainThread:1082 [wandb_setup.py:_flush():71] setting env: {}
2022-02-23 17:17:50,327 INFO    MainThread:1082 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-23 17:17:50,327 INFO    MainThread:1082 [wandb_init.py:_log_setup():371] Logging user logs to /home/simon/CDE_UBS/thesis/testing/wandb/run-20220223_171750-37mq8b4e/logs/debug.log
2022-02-23 17:17:50,327 INFO    MainThread:1082 [wandb_init.py:_log_setup():372] Logging internal logs to /home/simon/CDE_UBS/thesis/testing/wandb/run-20220223_171750-37mq8b4e/logs/debug-internal.log
2022-02-23 17:17:50,328 INFO    MainThread:1082 [wandb_init.py:init():404] calling init triggers
2022-02-23 17:17:50,328 INFO    MainThread:1082 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {}
2022-02-23 17:17:50,328 INFO    MainThread:1082 [wandb_init.py:init():426] re-initializing run, found existing run on stack: 8kdcfb4f
2022-02-23 17:17:50,330 INFO    MainThread:1082 [wandb_run.py:finish():1457] finishing run simon-donike/SRCNN/8kdcfb4f
2022-02-23 17:17:50,332 INFO    MainThread:1082 [jupyter.py:save_history():429] not saving jupyter history
2022-02-23 17:17:50,332 INFO    MainThread:1082 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-23 17:17:50,332 INFO    MainThread:1082 [wandb_init.py:_jupyter_teardown():303] cleaning up jupyter logic
2022-02-23 17:17:50,332 INFO    MainThread:1082 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-02-23 17:17:50,334 INFO    MainThread:1082 [wandb_run.py:_restore():1752] restore
2022-02-23 17:17:50,554 INFO    MainThread:1082 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 761
}

2022-02-23 17:17:50,832 INFO    MainThread:1082 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 761
}

2022-02-23 17:17:51,795 INFO    MainThread:1082 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 25181
}

2022-02-23 17:17:51,901 INFO    MainThread:1082 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 25181
}

2022-02-23 17:17:52,007 INFO    MainThread:1082 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 25181
}

2022-02-23 17:17:52,110 INFO    MainThread:1082 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25181
  total_bytes: 25181
}

2022-02-23 17:17:52,216 INFO    MainThread:1082 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25181
  total_bytes: 25181
}

2022-02-23 17:17:52,319 INFO    MainThread:1082 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25181
  total_bytes: 25181
}

2022-02-23 17:17:52,422 INFO    MainThread:1082 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25181
  total_bytes: 25181
}

2022-02-23 17:17:52,525 INFO    MainThread:1082 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25181
  total_bytes: 25181
}

2022-02-23 17:17:53,104 INFO    MainThread:1082 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25181
  total_bytes: 25181
}

2022-02-23 17:17:53,544 INFO    MainThread:1082 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25181
  total_bytes: 25181
}
local_info {
}

2022-02-23 17:17:55,350 INFO    MainThread:1082 [wandb_run.py:_append_files():2180] logging synced files
2022-02-23 17:17:55,372 INFO    MainThread:1082 [wandb_init.py:init():460] starting backend
2022-02-23 17:17:55,372 INFO    MainThread:1082 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-23 17:17:55,381 INFO    MainThread:1082 [backend.py:ensure_launched():216] starting backend process...
2022-02-23 17:17:55,439 INFO    MainThread:1082 [backend.py:ensure_launched():222] started backend process with pid: 1287
2022-02-23 17:17:55,444 INFO    MainThread:1082 [wandb_init.py:init():469] backend started and connected
2022-02-23 17:17:55,491 INFO    MainThread:1082 [wandb_run.py:_label_probe_notebook():911] probe notebook
2022-02-23 17:17:55,492 INFO    MainThread:1082 [wandb_run.py:_label_probe_notebook():921] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-02-23 17:17:55,492 INFO    MainThread:1082 [wandb_init.py:init():533] updated telemetry
2022-02-23 17:17:55,606 INFO    MainThread:1082 [wandb_init.py:init():563] communicating current version
2022-02-23 17:17:57,275 INFO    MainThread:1082 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.10 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-02-23 17:17:57,277 INFO    MainThread:1082 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-02-23 17:17:57,505 INFO    MainThread:1082 [wandb_init.py:init():606] starting run threads in backend
2022-02-23 17:18:02,517 INFO    MainThread:1082 [wandb_run.py:_console_start():1810] atexit reg
2022-02-23 17:18:02,519 INFO    MainThread:1082 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-02-23 17:18:02,519 INFO    MainThread:1082 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-02-23 17:18:02,522 INFO    MainThread:1082 [wandb_run.py:_redirect():1745] Redirects installed.
2022-02-23 17:18:02,522 INFO    MainThread:1082 [wandb_init.py:init():633] run started, returning control to user process
2022-02-23 17:28:23,949 INFO    MainThread:1082 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-02-23 17:28:23,951 INFO    MainThread:1082 [wandb_run.py:_restore():1752] restore
2022-02-23 17:28:24,658 INFO    MainThread:1082 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 761
}

2022-02-23 17:28:25,108 INFO    MainThread:1082 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 761
}

2022-02-23 17:28:25,965 INFO    MainThread:1082 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 9971
}

2022-02-23 17:28:26,069 INFO    MainThread:1082 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 25163
}

2022-02-23 17:28:26,173 INFO    MainThread:1082 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 25163
}

2022-02-23 17:28:26,275 INFO    MainThread:1082 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 25163
}

