2022-02-18 11:48:03,776 INFO    MainThread:11342 [wandb_setup.py:_flush():71] setting env: {}
2022-02-18 11:48:03,777 INFO    MainThread:11342 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-18 11:48:03,777 INFO    MainThread:11342 [wandb_init.py:_log_setup():371] Logging user logs to /home/simon/CDE_UBS/thesis/testing/wandb/run-20220218_114803-1dwjg9ha/logs/debug.log
2022-02-18 11:48:03,777 INFO    MainThread:11342 [wandb_init.py:_log_setup():372] Logging internal logs to /home/simon/CDE_UBS/thesis/testing/wandb/run-20220218_114803-1dwjg9ha/logs/debug-internal.log
2022-02-18 11:48:03,777 INFO    MainThread:11342 [wandb_init.py:_jupyter_setup():321] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fb0df3848d0>
2022-02-18 11:48:03,778 INFO    MainThread:11342 [wandb_init.py:init():404] calling init triggers
2022-02-18 11:48:03,778 INFO    MainThread:11342 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {}
2022-02-18 11:48:03,778 INFO    MainThread:11342 [wandb_init.py:init():460] starting backend
2022-02-18 11:48:03,778 INFO    MainThread:11342 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-18 11:48:03,865 INFO    MainThread:11342 [backend.py:ensure_launched():216] starting backend process...
2022-02-18 11:48:03,939 INFO    MainThread:11342 [backend.py:ensure_launched():222] started backend process with pid: 11399
2022-02-18 11:48:03,941 INFO    MainThread:11342 [wandb_init.py:init():469] backend started and connected
2022-02-18 11:48:03,976 INFO    MainThread:11342 [wandb_run.py:_label_probe_notebook():911] probe notebook
2022-02-18 11:48:03,977 INFO    MainThread:11342 [wandb_run.py:_label_probe_notebook():921] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-02-18 11:48:03,978 INFO    MainThread:11342 [wandb_init.py:init():533] updated telemetry
2022-02-18 11:48:04,093 INFO    MainThread:11342 [wandb_init.py:init():563] communicating current version
2022-02-18 11:48:06,034 INFO    MainThread:11342 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.10 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-02-18 11:48:06,037 INFO    MainThread:11342 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-02-18 11:48:06,263 INFO    MainThread:11342 [wandb_init.py:init():606] starting run threads in backend
2022-02-18 11:48:11,273 INFO    MainThread:11342 [wandb_run.py:_console_start():1810] atexit reg
2022-02-18 11:48:11,273 INFO    MainThread:11342 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-02-18 11:48:11,274 INFO    MainThread:11342 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-02-18 11:48:11,275 INFO    MainThread:11342 [wandb_run.py:_redirect():1745] Redirects installed.
2022-02-18 11:48:11,275 INFO    MainThread:11342 [wandb_init.py:init():633] run started, returning control to user process
2022-02-18 11:48:17,460 INFO    MainThread:11342 [wandb_init.py:_pause_backend():284] pausing backend
2022-02-18 11:48:17,460 INFO    MainThread:11342 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-18 11:48:34,085 INFO    MainThread:11342 [wandb_init.py:_resume_backend():293] resuming backend
2022-02-18 11:48:34,096 INFO    MainThread:11342 [wandb_init.py:_pause_backend():284] pausing backend
2022-02-18 11:48:34,096 INFO    MainThread:11342 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-18 11:48:34,774 INFO    MainThread:11342 [wandb_init.py:_resume_backend():293] resuming backend
2022-02-18 11:48:34,785 INFO    MainThread:11342 [wandb_init.py:_pause_backend():284] pausing backend
2022-02-18 11:48:34,785 INFO    MainThread:11342 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-18 11:48:35,817 INFO    MainThread:11342 [wandb_init.py:_resume_backend():293] resuming backend
2022-02-18 11:48:35,834 INFO    MainThread:11342 [wandb_setup.py:_flush():71] setting env: {}
2022-02-18 11:48:35,835 INFO    MainThread:11342 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-18 11:48:35,835 INFO    MainThread:11342 [wandb_init.py:_log_setup():371] Logging user logs to /home/simon/CDE_UBS/thesis/testing/wandb/run-20220218_114835-2m3ur0vd/logs/debug.log
2022-02-18 11:48:35,835 INFO    MainThread:11342 [wandb_init.py:_log_setup():372] Logging internal logs to /home/simon/CDE_UBS/thesis/testing/wandb/run-20220218_114835-2m3ur0vd/logs/debug-internal.log
2022-02-18 11:48:35,835 INFO    MainThread:11342 [wandb_init.py:init():404] calling init triggers
2022-02-18 11:48:35,835 INFO    MainThread:11342 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {}
2022-02-18 11:48:35,835 INFO    MainThread:11342 [wandb_init.py:init():426] re-initializing run, found existing run on stack: 1dwjg9ha
2022-02-18 11:48:35,837 INFO    MainThread:11342 [wandb_run.py:finish():1457] finishing run simon-donike/SRCNN/1dwjg9ha
2022-02-18 11:48:35,838 INFO    MainThread:11342 [jupyter.py:save_history():429] not saving jupyter history
2022-02-18 11:48:35,838 INFO    MainThread:11342 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-18 11:48:35,839 INFO    MainThread:11342 [wandb_init.py:_jupyter_teardown():303] cleaning up jupyter logic
2022-02-18 11:48:35,839 INFO    MainThread:11342 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-02-18 11:48:35,840 INFO    MainThread:11342 [wandb_run.py:_restore():1752] restore
2022-02-18 11:48:37,029 INFO    MainThread:11342 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  total_bytes: 761
}

2022-02-18 11:48:37,302 INFO    MainThread:11342 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 761
}

2022-02-18 11:48:37,406 INFO    MainThread:11342 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 25181
}

2022-02-18 11:48:37,510 INFO    MainThread:11342 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 25181
}

2022-02-18 11:48:37,612 INFO    MainThread:11342 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25181
  total_bytes: 25181
}

2022-02-18 11:48:37,717 INFO    MainThread:11342 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25181
  total_bytes: 25181
}

2022-02-18 11:48:37,819 INFO    MainThread:11342 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25181
  total_bytes: 25181
}

2022-02-18 11:48:37,922 INFO    MainThread:11342 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25181
  total_bytes: 25181
}

2022-02-18 11:48:38,025 INFO    MainThread:11342 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25181
  total_bytes: 25181
}

2022-02-18 11:48:38,128 INFO    MainThread:11342 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25181
  total_bytes: 25181
}

2022-02-18 11:48:38,638 INFO    MainThread:11342 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25181
  total_bytes: 25181
}

2022-02-18 11:48:39,085 INFO    MainThread:11342 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25181
  total_bytes: 25181
}
local_info {
}

2022-02-18 11:48:40,895 INFO    MainThread:11342 [wandb_run.py:_append_files():2180] logging synced files
