2022-02-24 22:52:09,630 INFO    MainThread:28352 [wandb_setup.py:_flush():71] setting env: {}
2022-02-24 22:52:09,630 INFO    MainThread:28352 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-24 22:52:09,630 INFO    MainThread:28352 [wandb_init.py:_log_setup():371] Logging user logs to /home/simon/CDE_UBS/thesis/template/wandb/run-20220224_225209-31h7zoz2/logs/debug.log
2022-02-24 22:52:09,631 INFO    MainThread:28352 [wandb_init.py:_log_setup():372] Logging internal logs to /home/simon/CDE_UBS/thesis/template/wandb/run-20220224_225209-31h7zoz2/logs/debug-internal.log
2022-02-24 22:52:09,631 INFO    MainThread:28352 [wandb_init.py:_jupyter_setup():321] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fc489029350>
2022-02-24 22:52:09,631 INFO    MainThread:28352 [wandb_init.py:init():404] calling init triggers
2022-02-24 22:52:09,631 INFO    MainThread:28352 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {}
2022-02-24 22:52:09,632 INFO    MainThread:28352 [wandb_init.py:init():460] starting backend
2022-02-24 22:52:09,632 INFO    MainThread:28352 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-24 22:52:09,693 INFO    MainThread:28352 [backend.py:ensure_launched():216] starting backend process...
2022-02-24 22:52:09,732 INFO    MainThread:28352 [backend.py:ensure_launched():222] started backend process with pid: 28409
2022-02-24 22:52:09,734 INFO    MainThread:28352 [wandb_init.py:init():469] backend started and connected
2022-02-24 22:52:09,798 INFO    MainThread:28352 [wandb_run.py:_label_probe_notebook():911] probe notebook
2022-02-24 22:52:09,799 INFO    MainThread:28352 [wandb_run.py:_label_probe_notebook():921] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-02-24 22:52:09,799 INFO    MainThread:28352 [wandb_init.py:init():533] updated telemetry
2022-02-24 22:52:09,912 INFO    MainThread:28352 [wandb_init.py:init():563] communicating current version
2022-02-24 22:52:11,822 INFO    MainThread:28352 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.10 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-02-24 22:52:11,824 INFO    MainThread:28352 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-02-24 22:52:12,040 INFO    MainThread:28352 [wandb_init.py:init():606] starting run threads in backend
2022-02-24 22:52:17,060 INFO    MainThread:28352 [wandb_run.py:_console_start():1810] atexit reg
2022-02-24 22:52:17,061 INFO    MainThread:28352 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-02-24 22:52:17,061 INFO    MainThread:28352 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-02-24 22:52:17,063 INFO    MainThread:28352 [wandb_run.py:_redirect():1745] Redirects installed.
2022-02-24 22:52:17,063 INFO    MainThread:28352 [wandb_init.py:init():633] run started, returning control to user process
2022-02-24 22:52:28,611 INFO    MainThread:28352 [wandb_init.py:_pause_backend():284] pausing backend
2022-02-24 22:52:28,611 INFO    MainThread:28352 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-24 22:52:55,981 INFO    MainThread:28352 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-02-24 22:52:55,983 INFO    MainThread:28352 [wandb_run.py:_restore():1752] restore
2022-02-24 22:52:56,122 INFO    MainThread:28352 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 761
}

2022-02-24 22:52:56,387 INFO    MainThread:28352 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 761
}

2022-02-24 22:52:57,110 INFO    MainThread:28352 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 10028
}

2022-02-24 22:52:57,217 INFO    MainThread:28352 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 25297
}

2022-02-24 22:52:57,324 INFO    MainThread:28352 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 25297
}

2022-02-24 22:52:57,427 INFO    MainThread:28352 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25297
  total_bytes: 25297
}

2022-02-24 22:52:57,531 INFO    MainThread:28352 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25297
  total_bytes: 25297
}

2022-02-24 22:52:57,634 INFO    MainThread:28352 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25297
  total_bytes: 25297
}

2022-02-24 22:52:57,737 INFO    MainThread:28352 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25297
  total_bytes: 25297
}

2022-02-24 22:52:57,840 INFO    MainThread:28352 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25297
  total_bytes: 25297
}

2022-02-24 22:52:57,943 INFO    MainThread:28352 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25297
  total_bytes: 25297
}

