2022-02-18 12:30:46,514 INFO    MainThread:13045 [wandb_setup.py:_flush():71] setting env: {}
2022-02-18 12:30:46,514 INFO    MainThread:13045 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-18 12:30:46,514 INFO    MainThread:13045 [wandb_init.py:_log_setup():371] Logging user logs to /home/simon/CDE_UBS/thesis/testing/wandb/run-20220218_123046-352en2j0/logs/debug.log
2022-02-18 12:30:46,515 INFO    MainThread:13045 [wandb_init.py:_log_setup():372] Logging internal logs to /home/simon/CDE_UBS/thesis/testing/wandb/run-20220218_123046-352en2j0/logs/debug-internal.log
2022-02-18 12:30:46,515 INFO    MainThread:13045 [wandb_init.py:_jupyter_setup():321] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f92e4065cd0>
2022-02-18 12:30:46,515 INFO    MainThread:13045 [wandb_init.py:init():404] calling init triggers
2022-02-18 12:30:46,516 INFO    MainThread:13045 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {}
2022-02-18 12:30:46,516 INFO    MainThread:13045 [wandb_init.py:init():460] starting backend
2022-02-18 12:30:46,516 INFO    MainThread:13045 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-18 12:30:46,574 INFO    MainThread:13045 [backend.py:ensure_launched():216] starting backend process...
2022-02-18 12:30:46,611 INFO    MainThread:13045 [backend.py:ensure_launched():222] started backend process with pid: 13090
2022-02-18 12:30:46,613 INFO    MainThread:13045 [wandb_init.py:init():469] backend started and connected
2022-02-18 12:30:46,652 INFO    MainThread:13045 [wandb_run.py:_label_probe_notebook():911] probe notebook
2022-02-18 12:30:46,654 INFO    MainThread:13045 [wandb_run.py:_label_probe_notebook():921] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-02-18 12:30:46,654 INFO    MainThread:13045 [wandb_init.py:init():533] updated telemetry
2022-02-18 12:30:46,745 INFO    MainThread:13045 [wandb_init.py:init():563] communicating current version
2022-02-18 12:30:48,683 INFO    MainThread:13045 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.10 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-02-18 12:30:48,686 INFO    MainThread:13045 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-02-18 12:30:48,917 INFO    MainThread:13045 [wandb_init.py:init():606] starting run threads in backend
2022-02-18 12:30:53,932 INFO    MainThread:13045 [wandb_run.py:_console_start():1810] atexit reg
2022-02-18 12:30:53,933 INFO    MainThread:13045 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-02-18 12:30:53,934 INFO    MainThread:13045 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-02-18 12:30:53,935 INFO    MainThread:13045 [wandb_run.py:_redirect():1745] Redirects installed.
2022-02-18 12:30:53,935 INFO    MainThread:13045 [wandb_init.py:init():633] run started, returning control to user process
2022-02-18 12:30:55,426 INFO    MainThread:13045 [wandb_init.py:_pause_backend():284] pausing backend
2022-02-18 12:30:55,427 INFO    MainThread:13045 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-18 12:31:44,348 INFO    MainThread:13045 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-02-18 12:31:44,350 INFO    MainThread:13045 [wandb_run.py:_restore():1752] restore
2022-02-18 12:31:45,004 INFO    MainThread:13045 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 761
}

2022-02-18 12:31:45,236 INFO    MainThread:13045 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 761
}

2022-02-18 12:31:45,973 INFO    MainThread:13045 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 25162
}

2022-02-18 12:31:46,079 INFO    MainThread:13045 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 25162
}

2022-02-18 12:31:46,188 INFO    MainThread:13045 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 25162
}

2022-02-18 12:31:46,291 INFO    MainThread:13045 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25162
  total_bytes: 25162
}

2022-02-18 12:31:46,396 INFO    MainThread:13045 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25162
  total_bytes: 25162
}

2022-02-18 12:31:46,500 INFO    MainThread:13045 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25162
  total_bytes: 25162
}

2022-02-18 12:31:46,602 INFO    MainThread:13045 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25162
  total_bytes: 25162
}

2022-02-18 12:31:46,705 INFO    MainThread:13045 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25162
  total_bytes: 25162
}

